SELECT [Id]
      ,[Environment]
      ,[FullName]
      ,[vCenter]
      ,[HostName]
      ,[Model]
      ,[Cluster]
      ,[MemorySize]
      ,[CPUModel]
      ,[BIOSDate]
      ,[BIOSVer]
      ,[ESXiVer]
      ,[ESXiBuild]
      ,[PowerRegulator]
      ,[PowerProfile]
      ,[PowerSupport]
      ,[SerialNum]
      ,[IPAddress]
      ,[NicDriver]
      ,[NicFirmware]
      ,[Nic2Driver]
      ,[Nic2Firmware]
      ,[HPSADriver]
      ,[HPSAFirmware]
      ,[iLOFirmware]
      ,[iLODNS]
      ,[HPAMS]
      ,[CiscoVDS]
      ,[Enclosure]
      ,[ServerBay]
      ,[EVCModeCluster]
      ,[EVCMax]
      ,[IOVRuntime]
      ,[HUptime]
      ,[CPUCores]
      ,[CPUSockets]
      ,[CPUThread]
      ,[CPUSpeed]
      ,[WWN1]
      ,[WWN2]
      ,[MACAddr1]
      ,[MACAddr2]
      ,[ConfigStandard]
      ,[NetSum]
      ,[HBASum]
      ,[CPUSum]
      ,[Switches]
      ,[HPSAModel]
      ,[HWStatus]
      ,[CfgSettings]
      ,[Vibs]
      ,[MoRef]
      ,[DtUpdated]
      ,[IsActive]
  FROM [VMInventory].[dbo].[HostHw]

  where Environment = 'RHO'
  and Cluster not like '%Build%'
  and Cluster not like '%RDS%'
  and Cluster not like '%PPM%'
  --and Cluster not like '%1CI-%'
  --and Cluster not like '%2CI-%'
  --and Cluster not like '%3CI-%'
  --and Cluster not like '%4CI-%'
  --and Cluster not like '%5CI-%'